server:
  port: 8084

spring:
  application:
    name: ${spring-application-name}
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-service-url}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}
    hostname: k9A603.p.ssafy.io

openapi:
  service:
    version: ${openapi-service-version}
    url: ${openapi-service-url} # api gateway url

logging:
  level:
    kr.co.kr.co.tunemate.tunemategroupservice: debug
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
